package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"sort"
	"strings"
)

var packageDirs = []string{
	"protocol", "store", "store/fs", "store/s3", "store/gcs",
	"repository", "broker/client", "broker/capability", "broker/local", "transport",
}

func main() {
	check := flag.String("check", "", "verify that a generated API inventory matches this file")
	flag.Parse()
	var output bytes.Buffer
	fmt.Fprintln(&output, "# BucketGit Exported Go API")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "Generated by `go run ./tools/api_inventory`. This is the public BucketGit Go SDK v1 compatibility surface.")
	for _, directory := range packageDirs {
		symbols, err := exportedSymbols(directory)
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		fmt.Fprintf(&output, "\n## `github.com/bucketgit/bgit/%s`\n\n", directory)
		for _, symbol := range symbols {
			fmt.Fprintf(&output, "- `%s`\n", symbol)
		}
	}
	if *check != "" {
		current, err := os.ReadFile(*check)
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		if !bytes.Equal(current, output.Bytes()) {
			fmt.Fprintf(os.Stderr, "%s is stale; regenerate it with `go run ./tools/api_inventory > %s`\n", *check, *check)
			os.Exit(1)
		}
		return
	}
	_, _ = os.Stdout.Write(output.Bytes())
}

func exportedSymbols(directory string) ([]string, error) {
	set := token.NewFileSet()
	packages, err := parser.ParseDir(set, directory, func(info os.FileInfo) bool {
		return !strings.HasSuffix(info.Name(), "_test.go")
	}, 0)
	if err != nil {
		return nil, fmt.Errorf("parse %s: %w", directory, err)
	}
	var symbols []string
	for _, parsed := range packages {
		for _, file := range parsed.Files {
			for _, declaration := range file.Decls {
				switch value := declaration.(type) {
				case *ast.FuncDecl:
					if !ast.IsExported(value.Name.Name) {
						continue
					}
					if value.Recv == nil {
						symbols = append(symbols, "func "+value.Name.Name)
					} else {
						receiver := receiverName(value.Recv.List[0].Type)
						if ast.IsExported(receiver) {
							symbols = append(symbols, "method "+receiver+"."+value.Name.Name)
						}
					}
				case *ast.GenDecl:
					for _, specification := range value.Specs {
						switch spec := specification.(type) {
						case *ast.TypeSpec:
							if ast.IsExported(spec.Name.Name) {
								symbols = append(symbols, "type "+spec.Name.Name)
							}
						case *ast.ValueSpec:
							for _, name := range spec.Names {
								if ast.IsExported(name.Name) {
									symbols = append(symbols, strings.ToLower(value.Tok.String())+" "+name.Name)
								}
							}
						}
					}
				}
			}
		}
	}
	sort.Strings(symbols)
	return symbols, nil
}

func receiverName(expression ast.Expr) string {
	switch value := expression.(type) {
	case *ast.Ident:
		return value.Name
	case *ast.StarExpr:
		return receiverName(value.X)
	default:
		return "receiver"
	}
}
