#!/usr/bin/env bash
source "$(dirname "$0")/../lib/testlib.sh"
init_output="$(init_bgit_repo gcp whoami)"
dir="$(printf "%s\n" "$init_output" | sed -n "1p")"
repo="$(printf "%s\n" "$init_output" | sed -n "2p")"
repo_display="${repo%.git}"
add_key_to_repo "$dir" developer developer developer
out="$(run_in "$dir" whoami)"
assert_contains "$out" "role"
assert_contains "$out" "role: admin"
out="$(run_in "$dir" whoami --json --refresh)"
assert_contains "$out" "\"role\": \"admin\""
assert_contains "$out" "\"capabilities\""
out="$(run_in "$dir" whoami --all)"
assert_contains "$out" "$repo"
out="$(run_in "$dir" whoami --all --json)"
assert_contains "$out" "\"repos\""
assert_contains "$out" "$repo"
out="$(run_in "$dir" repos mine)"
assert_contains "$out" "$repo"
out="$(run_in "$dir" repos mine --json)"
assert_contains "$out" "\"repos\""
assert_contains "$out" "$repo"
out="$(run_in "$dir" admin repo list)"
assert_contains "$out" "$repo_display"
out="$(run_in "$dir" admin repo info)"
assert_contains "$out" "repository:"
assert_contains "$out" "visibility:"
out="$(run_in "$dir" admin teams repo list)"
assert_contains "$out" "t_core"
out="$(run_in "$dir" janitor members reindex)"
assert_contains "$out" "reindexed broker membership"
out="$(expect_failure_no_agent "$dir" whoami --refresh)"
assert_contains "$out" "SSH signature required"
out="$(expect_failure_no_agent "$dir" repos mine)"
assert_contains "$out" "no SSH agent keys available"
out="$(expect_failure_in_as developer "$dir" admin repo list)"
assert_contains "$out" "broker admin SSH signature required"
out="$(expect_failure_in_as developer "$dir" janitor members reindex)"
assert_contains "$out" "admin SSH signature required"
