#!/usr/bin/env bash
source "$(dirname "$0")/../lib/testlib.sh"
init_output="$(init_bgit_repo aws init)"
dir="$(printf "%s\n" "$init_output" | sed -n "1p")"
repo="$(printf "%s\n" "$init_output" | sed -n "2p")"
assert_file_exists "$dir/.git/config"
out="$(git -C "$dir" config --get bucketgit.logicalRepo)"
assert_contains "$out" "$repo"
out="$(git -C "$dir" config --get bucketgit.broker)"
assert_contains "$out" "http"
out="$(git -C "$dir" config --get bucketgit.team)"
assert_contains "$out" "t_core"

bad_dir="$(new_workdir aws init-path-rejected)"
out="$(expect_failure "$BGIT" init --noninteractive --repo team/app --profile "$AWS_PROFILE" --team core "${CONFIG_ARGS[@]}" "$bad_dir")"
assert_contains "$out" "logical repo names must be flat"

missing_dir="$(new_workdir aws init-missing-repo)"
out="$(expect_failure "$BGIT" init --noninteractive --repo "$(new_repo_name aws init-missing-repo)" --profile "$AWS_PROFILE" --team core "${CONFIG_ARGS[@]}" "$missing_dir")"
assert_contains "$out" "repository not found"
assert_file_not_exists "$missing_dir/.git"

created_repo="$(new_repo_name aws explicit-create)"
out="$(expect_success "$BGIT" --profile "$AWS_PROFILE" admin repo create --team core "$created_repo")"
assert_contains "$out" "created repository"
created_dir="$(new_workdir aws explicit-create)"
expect_success "$BGIT" init --noninteractive --repo "$created_repo" --profile "$AWS_PROFILE" --team core "${CONFIG_ARGS[@]}" "$created_dir" >/dev/null
out="$(expect_failure "$BGIT" --profile "$AWS_PROFILE" admin repo create --team core "$created_repo")"
assert_contains "$out" "repository already exists"
out="$(expect_failure "$BGIT" --profile "$AWS_PROFILE" admin repo create --team core --role madeup "$(new_repo_name aws invalid-role)")"
assert_contains "$out" "invalid repo team role"
out="$(expect_failure "$BGIT" --profile "$AWS_PROFILE" admin repo create --team missing-team "$(new_repo_name aws invalid-team)")"
assert_contains "$out" "team not found"
