#!/usr/bin/env bash
source "$(dirname "$0")/../lib/testlib.sh"
init_output="$(init_bgit_repo aws init)"
dir="$(printf "%s\n" "$init_output" | sed -n "1p")"
repo="$(printf "%s\n" "$init_output" | sed -n "2p")"
assert_file_exists "$dir/.git/config"
out="$(git -C "$dir" config --get bucketgit.logicalRepo)"
assert_contains "$out" "$repo"
out="$(git -C "$dir" config --get bucketgit.broker)"
assert_contains "$out" "http"
