name: Test

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  unit:
    name: Unit Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - macos-15-intel
          - ubuntu-24.04
          - windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Unit Tests
        run: go test ./...

  local-broker-integration:
    name: Local Broker Integration (${{ matrix.runtime }} / ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - macos-15-intel
          - ubuntu-24.04
          - windows-2022
        runtime:
          - gcp
          - aws
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 25

      - name: Local Broker Integration
        shell: bash
        run: ./testsuite/run-local-broker.sh "${{ matrix.runtime }}"
