#!/usr/bin/env bash
set -euo pipefail
provider="$1"
source "$(dirname "$0")/../testlib.sh"

init_output="$(init_bgit_repo "$provider" invites-ownership)"
dir="$(printf "%s\n" "$init_output" | sed -n "1p")"
repo="$(printf "%s\n" "$init_output" | sed -n "2p")"
broker="$(git -C "$dir" config --get bucketgit.broker)"

out="$(run_in "$dir" admin invite-user --broker "$broker" --user invited-dev --role developer "$repo")"
assert_contains "$out" "bgit admin accept-invite"
invite_code="$(printf '%s\n' "$out" | awk '/accept-invite/ {print $NF; exit}')"
[[ "$invite_code" == bgitinv_* ]] || fail "invite code not found in output: $out"
out="$(expect_failure "$BGIT" admin invite-user --broker "$broker" --user bad-role --role madeup "$repo")"
assert_contains "$out" "invalid role"
out="$(expect_failure "$BGIT" admin invite-user --broker "$broker" --user invited-dev --role read "$repo")"
assert_contains "$out" "invite already pending for user"
cancel_out="$(run_in "$dir" admin invite-user --broker "$broker" --user cancelled-dev --role developer "$repo")"
cancel_code="$(printf '%s\n' "$cancel_out" | awk '/accept-invite/ {print $NF; exit}')"
out="$(run_in "$dir" admin cancel-invite --user cancelled-dev)"
assert_contains "$out" "cancelled invite for cancelled-dev"
out="$(with_agent_key maintainer expect_failure "$BGIT" admin accept-invite "$cancel_code")"
assert_contains "$out" "invite is not pending or has expired"
cancel_out="$(run_in "$dir" admin invite-user --broker "$broker" --user code-cancelled --role read "$repo")"
cancel_code="$(printf '%s\n' "$cancel_out" | awk '/accept-invite/ {print $NF; exit}')"
out="$(expect_failure "$BGIT" admin cancel-invite "$cancel_code")"
assert_contains "$out" "usage: bgit admin cancel-invite --broker URL [--team TEAM] --user USER REPO"
out="$(run_in "$dir" admin cancel-invite --user code-cancelled)"
assert_contains "$out" "cancelled invite for code-cancelled"
out="$(with_agent_key maintainer expect_failure "$BGIT" admin accept-invite "$cancel_code")"
assert_contains "$out" "invite is not pending or has expired"
out="$(without_ssh_identity expect_failure "$BGIT" admin accept-invite "$invite_code")"
assert_contains "$out" "SSH signature required"
out="$(with_agent_key outsider "$BGIT" admin accept-invite "$invite_code")"
assert_contains "$out" "accepted invite for invited-dev as developer"
out="$(expect_failure_in_as outsider "$dir" admin accept-invite "$invite_code")"
assert_contains "$out" "invite is not pending or has expired"
out="$(run_in_as outsider "$dir" whoami --refresh)"
assert_contains "$out" "user: invited-dev"
assert_contains "$out" "role: developer"

out="$(run_in "$dir" admin invite-broker-user --broker "$broker" --user pending-team --role user)"
assert_contains "$out" "bgit admin accept-broker-invite"
broker_invite_code="$(printf '%s\n' "$out" | awk '/accept-broker-invite/ {print $NF; exit}')"
[[ "$broker_invite_code" == bgituser_* ]] || fail "broker invite code not found in output: $out"
out="$(expect_failure "$BGIT" admin invite-broker-user --broker "$broker" --user wrong-role --role madeup)"
assert_contains "$out" "invalid broker role"
cancel_broker_out="$(run_in "$dir" admin invite-broker-user --broker "$broker" --user cancelled-broker --role user)"
cancel_broker_code="$(printf '%s\n' "$cancel_broker_out" | awk '/accept-broker-invite/ {print $NF; exit}')"
out="$(run_in "$dir" admin cancel-broker-invite --broker "$broker" --user cancelled-broker)"
assert_contains "$out" "cancelled broker invite for cancelled-broker"
out="$(with_agent_key read expect_failure "$BGIT" admin accept-broker-invite "$cancel_broker_code")"
assert_contains "$out" "broker user invite is not pending"
out="$(run_in "$dir" admin broker-users list)"
assert_not_contains "$out" "cancelled-broker"
out="$(run_in_as read "$dir" repos mine --json)"
assert_not_contains "$out" "$repo"
team_out="$(run_in "$dir" admin teams create pending-team-access)"
team_id="$(printf '%s\n' "$team_out" | awk -F'[()]' '{print $2; exit}')"
[[ "$team_id" == t_* ]] || fail "team id not found in output: $team_out"
run_in "$dir" admin teams member add "$team_id" pending-team --role developer >/dev/null
run_in "$dir" admin teams repo add "$team_id" developer >/dev/null
out="$(expect_failure_in_as read "$dir" whoami --refresh)"
assert_contains "$out" "SSH signature required"
out="$(with_agent_key read "$BGIT" admin accept-broker-invite "$broker_invite_code")"
assert_contains "$out" "accepted broker invite for pending-team as user"
out="$(run_in_as read "$dir" whoami --refresh)"
assert_contains "$out" "user: pending-team"
assert_contains "$out" "role: developer"
out="$(run_in_as read "$dir" whoami --all --json)"
assert_contains "$out" "\"user\": \"pending-team\""
assert_contains "$out" "\"role\": \"developer\""
out="$(run_in_as read "$dir" repos mine --json)"
assert_contains "$out" "\"user\": \"pending-team\""
assert_contains "$out" "$repo"

out="$(run_in "$dir" admin confirm-ownership-transfer --broker "$broker" "$repo")"
assert_contains "$out" "ownership transfer pending"
transfer_code="$(printf '%s\n' "$out" | awk '/accept-ownership-transfer/ {print $NF; exit}')"
[[ "$transfer_code" == bgitot_* ]] || fail "ownership transfer code not found in output: $out"
out="$(expect_failure "$BGIT" admin confirm-ownership-transfer --broker "$broker" does-not-exist)"
assert_contains "$out" "repository not found"
out="$(expect_failure "$BGIT" admin confirm-ownership-transfer --broker "$broker" "$repo")"
assert_contains "$out" "ownership transfer already pending"
out="$(run_in "$dir" admin cancel-ownership-transfer --broker "$broker" "$repo")"
assert_contains "$out" "cancelled pending ownership transfer"
out="$(with_agent_key outsider expect_failure "$BGIT" admin accept-ownership-transfer "$transfer_code")"
assert_contains "$out" "ownership transfer is not pending or has expired"

out="$(run_in "$dir" admin confirm-ownership-transfer --broker "$broker" "$repo")"
transfer_code="$(printf '%s\n' "$out" | awk '/accept-ownership-transfer/ {print $NF; exit}')"
out="$(with_agent_key outsider expect_failure "$BGIT" admin accept-ownership-transfer "$transfer_code")"
assert_contains "$out" "SSH key already belongs to user invited-dev"
out="$(with_agent_key maintainer "$BGIT" admin accept-ownership-transfer "$transfer_code")"
assert_contains "$out" "accepted ownership for $repo"
out="$(run_in_as maintainer "$dir" whoami --refresh)"
assert_contains "$out" "role: owner"
out="$(run_in "$dir" whoami --refresh)"
assert_contains "$out" "role: admin"
out="$(run_in "$dir" admin confirm-ownership-transfer --broker "$broker" "$repo")"
assert_contains "$out" "ownership transfer pending"
run_in "$dir" admin cancel-ownership-transfer --broker "$broker" "$repo" >/dev/null
