#!/usr/bin/env bash
set -euo pipefail
provider="$1"
source "$(dirname "$0")/../testlib.sh"

init_output="$(init_bgit_repo "$provider" invites-ownership)"
dir="$(printf "%s\n" "$init_output" | sed -n "1p")"
repo="$(printf "%s\n" "$init_output" | sed -n "2p")"
broker="$(git -C "$dir" config --get bucketgit.broker)"

out="$(run_in "$dir" admin invite-user --broker "$broker" --user invited-dev --role developer "$repo")"
assert_contains "$out" "bgit admin accept-invite"
invite_code="$(printf '%s\n' "$out" | awk '/accept-invite/ {print $NF; exit}')"
[[ "$invite_code" == bgitinv_* ]] || fail "invite code not found in output: $out"
out="$(expect_failure "$BGIT" admin invite-user --broker "$broker" --user invited-dev --role read "$repo")"
assert_contains "$out" "invite already pending for user"
cancel_out="$(run_in "$dir" admin invite-user --broker "$broker" --user cancelled-dev --role developer "$repo")"
cancel_code="$(printf '%s\n' "$cancel_out" | awk '/accept-invite/ {print $NF; exit}')"
out="$(run_in "$dir" admin cancel-invite --user cancelled-dev)"
assert_contains "$out" "cancelled invite for cancelled-dev"
out="$(with_agent_key maintainer expect_failure "$BGIT" admin accept-invite "$cancel_code")"
assert_contains "$out" "invite is not pending or has expired"
cancel_out="$(run_in "$dir" admin invite-user --broker "$broker" --user code-cancelled --role read "$repo")"
cancel_code="$(printf '%s\n' "$cancel_out" | awk '/accept-invite/ {print $NF; exit}')"
out="$(expect_failure "$BGIT" admin cancel-invite "$cancel_code")"
assert_contains "$out" "usage: bgit admin cancel-invite --broker URL --user USER REPO"
out="$(run_in "$dir" admin cancel-invite --user code-cancelled)"
assert_contains "$out" "cancelled invite for code-cancelled"
out="$(with_agent_key maintainer expect_failure "$BGIT" admin accept-invite "$cancel_code")"
assert_contains "$out" "invite is not pending or has expired"
out="$(SSH_AUTH_SOCK= expect_failure "$BGIT" admin accept-invite "$invite_code")"
assert_contains "$out" "SSH signature required"
out="$(with_agent_key outsider "$BGIT" admin accept-invite "$invite_code")"
assert_contains "$out" "accepted invite for invited-dev as developer"
out="$(expect_failure_in_as outsider "$dir" admin accept-invite "$invite_code")"
assert_contains "$out" "invite is not pending or has expired"
out="$(run_in_as outsider "$dir" whoami --refresh)"
assert_contains "$out" "user: invited-dev"
assert_contains "$out" "role: developer"

out="$(run_in "$dir" admin confirm-ownership-transfer --broker "$broker" "$repo")"
assert_contains "$out" "ownership transfer pending"
transfer_code="$(printf '%s\n' "$out" | awk '/accept-ownership-transfer/ {print $NF; exit}')"
[[ "$transfer_code" == bgitot_* ]] || fail "ownership transfer code not found in output: $out"
out="$(expect_failure "$BGIT" admin confirm-ownership-transfer --broker "$broker" "$repo")"
assert_contains "$out" "ownership transfer already pending"
out="$(run_in "$dir" admin cancel-ownership-transfer --broker "$broker" "$repo")"
assert_contains "$out" "cancelled pending ownership transfer"
out="$(with_agent_key outsider expect_failure "$BGIT" admin accept-ownership-transfer "$transfer_code")"
assert_contains "$out" "ownership transfer is not pending or has expired"

out="$(run_in "$dir" admin confirm-ownership-transfer --broker "$broker" "$repo")"
transfer_code="$(printf '%s\n' "$out" | awk '/accept-ownership-transfer/ {print $NF; exit}')"
out="$(with_agent_key outsider "$BGIT" admin accept-ownership-transfer "$transfer_code")"
assert_contains "$out" "accepted ownership for $repo"
out="$(run_in_as outsider "$dir" whoami --refresh)"
assert_contains "$out" "role: owner"
out="$(run_in "$dir" whoami --refresh)"
assert_contains "$out" "role: admin"
out="$(expect_failure "$BGIT" admin confirm-ownership-transfer --broker "$broker" "$repo")"
assert_contains "$out" "owner SSH signature required"
